#!/bin/sh

set -eu

die() {
    exit "$1"
}

trap 'die $?' EXIT

parse_commitish() {
    case "$1" in
        ROOT)
            # NOTE: This could return more than one commit (e.g. if there is an octopus
            # merge).  Would be good to assert that this returns one commit.
            git rev-list --max-parents=0 HEAD
            ;;
        *)
            if ! git rev-parse "$1" >/dev/null 2>&1; then
                echo "can't find revision '$1'" 1>&2
                exit 1
            fi
            git rev-parse "$1"
            ;;
    esac
}

if test "$#" -eq 0 || test "$#" -gt 2 ; then
    echo "Usage: git-squash-range [<commit>] <commit>" 1>&2
    exit 1
fi

left=$(parse_commitish "ROOT")
if test "$#" -eq 2; then
    left=$(parse_commitish $1)
    shift
fi
right=$(parse_commitish $1)

commits_between=$(git rev-list --count $left..$right)
if test "$commits_between" -eq 0; then
    echo "nothing to squash" 1>&2
    exit 1
fi

head=$(git rev-parse HEAD)
branch=$(git branch --show-current)

short_left=$(git rev-parse --short $left)
short_right=$(git rev-parse --short $right)
short_head=$(git rev-parse --short $head)
left_count=$(git rev-list --count $right)
right_count=$(git rev-list --count $right..$head)
echo "Squashing the $left_count oldest commits [$short_left,$short_right] into a single commit"
echo "Preserving the $right_count newest commits commits ($short_right,$short_head]"

# Squash oldest commits
git checkout --quiet $left
git merge --quiet --squash $right >/dev/null
git commit --quiet --amend --allow-empty --reset-author -m Squashed >/dev/null

# Preserve newest commits
git cherry-pick --quiet $right..$head >/dev/null

# Move branch to new head
git branch --force $branch HEAD
git checkout --quiet $branch
