= Commit Management for GitHub Pages
:imagesdir: images

When GitHub Pages is served from a dedicated branch (e.g. `gh-pages`), we are free to rewrite its history to manage repository size.
One way to do this is to simply amend the HEAD commit and force push.

[source,sh]
----
git commit --amend --message "update GitHub Pages"
git push --force origin gh-pages
----

The upside to this is that previous updates no longer contribute to the repository size.
The downside to this is that we can't easily undo a bad commit.

To have the best of both worlds, we can take a more sophisticated approach.
Instead of squashing all of our changes into a single commit, we can preserve the N most recent commits and only squash the oldest commits.

The `git-squash-all-except` script provided here does exactly this.

image::squash-all-except.drawio.svg[]

== Algorithm

The history can be divided into two commit ranges:

* The oldest commits to be squashed: [root, mid]
* The newest commits to be preserved: (mid, head]

The commit IDs for the root, mid, and head commits are determined as follows:

* root - `git rev-list --max-parents=0 HEAD`
* mid - `git rev-parse HEAD~$N` where `N` is the number of commits we want to preserve
* head - `git rev-parse HEAD`

First, the oldest commits are squashed by checking out the root commit, performing a squash merge of mid, then amending the root commit with the result of the merge.

Then we cherry pick the newest commits on to our squashed commit.

Finally we move the branch to the HEAD commit.
