#!/bin/sh

set -e

make_test_repo() {
    echo "Creating a repository with a single initial commit"
    mkdir repo
    cd repo
    git init --quiet

    git config user.name name
    git config user.email email

    touch .gitignore
    git add .gitignore
    git commit --quiet --message initial

    git branch -M gh-pages

    cd -
}

add_test_commits() {
    start=$1
    finish=$2
    N=$(echo $2 - $1 + 1 | bc -l)
    echo "Adding $N commits"
    cd repo
    for i in $(seq $start $finish); do
        filename="$i-$(shuf -i 1-100000 -n 1)"
        touch $filename
        git add $filename
        git commit --quiet --message $filename
    done
    cd -
}

make_test_repo
git -C repo log --oneline
add_test_commits 0 3
git -C repo log --oneline
(cd repo && ../git-squash-oldest 3)
git -C repo log --oneline
add_test_commits 4 4
git -C repo log --oneline
(cd repo && ../git-squash-oldest 3)
git -C repo log --oneline
add_test_commits 5 5
git -C repo log --oneline
(cd repo && ../git-squash-oldest 3)
git -C repo log --oneline
